/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseFilter: typeof import('./src/components/BaseFilter.vue')['default']
    BaseLabel: typeof import('./src/components/BaseLabel.vue')['default']
    BaseLine: typeof import('./src/components/BaseLine.vue')['default']
    BaseMap: typeof import('./src/components/BaseMap.vue')['default']
    BaseStatistics: typeof import('./src/components/BaseStatistics.vue')['default']
    BaseTable: typeof import('./src/components/BaseTable.vue')['default']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
  }
}
